### PR TITLE
Use helm's json output

### LINKED ISSUE #61: Release is always marked to be purged and installed again.
Helmsman version: v1.3.0-rc
Helmsman version: v1.4.0-rc
OS: OSX 10.13.6
```bash
kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
```bash
helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

This is the content of  my Helmsman desired state file `myfile.yaml`:
```yaml
apps:
  artifactory:
    chart: stable/artifactory
    description: artifactory
    enabled: true
    name: artifactory
    namespace: test1
    priority: -2
    purge: true
    test: false
    valuesFile: ''
    version: 7.0.6
certificates: null
helmRepos:
  incubator: http://storage.googleapis.com/kubernetes-charts-incubator
  stable: https://kubernetes-charts.storage.googleapis.com
metadata:
  description: example Desired State File for demo purposes.
  maintainer: k8s-admin (me@example.com)
  org: example.com
namespaces:
  logging:
    installTiller: false
    protected: false
  monitoring:
    installTiller: false
    protected: false
  production:
    protected: true
  test1:
    installTiller: true
settings:
  kubeContext: k8s-quicktest
  storageBackend: secret
```

Hi, I'm testing Helmsman and I spotted that after the first run when the app is deployed and running every time I run `helmsman -f myfile.yaml` it shows the following message:

```bash
./helmsman -f myfile.yaml
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_|version: v1.3.0-rc
A Helm-Charts-as-Code tool.


2018/08/23 14:25:06 INFO: Parsed YAML [[ myfile.yaml ]] successfully and found [ 1 ] apps.
2018/08/23 14:25:06 INFO: naemspace validation -- Tiller is not desired to be deployed in namespace [ logging ].
2018/08/23 14:25:06 INFO: naemspace validation -- Tiller is not desired to be deployed in namespace [ monitoring ].
2018/08/23 14:25:06 INFO: naemspace validation -- Tiller is not desired to be deployed in namespace [ production ].
2018/08/23 14:25:06 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ test1 ].
2018/08/23 14:25:10 WARN: I could not create namespace [logging ]. It already exists. I am skipping this.
2018/08/23 14:25:10 WARN: I could not create namespace [monitoring ]. It already exists. I am skipping this.
2018/08/23 14:25:11 WARN: I could not create namespace [production ]. It already exists. I am skipping this.
2018/08/23 14:25:11 WARN: I could not create namespace [test1 ]. It already exists. I am skipping this.
2018/08/23 14:25:11 INFO: deploying shared Tiller on namespace [ kube-system ].
2018/08/23 14:25:12 INFO: deploying Tiller on namespace [ test1 ].
2018/08/23 14:25:22 INFO: checking what I need to do for your charts ...
2018/08/23 14:25:22 INFO: mapping the current helm state ...
2018/08/23 14:25:27 INFO: sorting the commands in the plan based on priorities (order flags) ...
----------------------
2018/08/23 14:25:27 INFO: Plan generated at: Thu Aug 23 2018 14:25:22
DECISION: release [ artifactory ] will be deleted from namespace [[ 5.9.1 ]] and reinstalled in [[ test1]]. -- priority: -2
WARNING: moving release [ artifactory ] from [[ 5.9.1 ]] to [[ test1 ]] might not correctly connect to existing volumes. Check https://github.com/Praqma/helmsman/blob/master/docs/how_to/move_charts_across_namespaces.md for details if this release uses PV and PVC. -- priority: -2
2018/08/23 14:25:27 INFO: completed successfully!
```

```bash
helmsman -f myfile.yaml
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_|version: v1.4.0-rc
A Helm-Charts-as-Code tool.


2018/08/23 14:25:47 INFO: Parsed YAML [[ myfile.yaml ]] successfully and found [ 1 ] apps.
2018/08/23 14:25:47 INFO: namespace validation -- Tiller is not desired to be deployed in namespace [ logging ].
2018/08/23 14:25:47 INFO: namespace validation -- Tiller is not desired to be deployed in namespace [ monitoring ].
2018/08/23 14:25:47 INFO: namespace validation -- Tiller is not desired to be deployed in namespace [ production ].
2018/08/23 14:25:47 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ test1 ].
2018/08/23 14:25:47 WARN: I could not create namespace [production ]. It already exists. I am skipping this.
2018/08/23 14:25:48 WARN: I could not create namespace [test1 ]. It already exists. I am skipping this.
2018/08/23 14:25:48 WARN: I could not create namespace [logging ]. It already exists. I am skipping this.
2018/08/23 14:25:49 WARN: I could not create namespace [monitoring ]. It already exists. I am skipping this.
2018/08/23 14:25:49 INFO: deploying Tiller in namespace [ kube-system ].
2018/08/23 14:25:50 INFO: deploying Tiller in namespace [ test1 ].
2018/08/23 14:25:59 INFO: checking what I need to do for your charts ...
2018/08/23 14:26:00 INFO: mapping the current helm state ...
2018/08/23 14:26:04 INFO: checking if any Helmsman managed releases are no longer tracked by your desired state ...
2018/08/23 14:26:05 INFO: no untracked releases found.
2018/08/23 14:26:05 INFO: sorting the commands in the plan based on priorities (order flags) ...
----------------------
2018/08/23 14:26:05 INFO: Plan generated at: Thu Aug 23 2018 13:25:59
DECISION: release [ artifactory ] is desired to be enabled in a new namespace [[ test1 ]]. I am planning a purge delete of the current release from namespace [[ 5.9.1 ]] and will install it for you in namespace [[ test1 ]] -- priority: -2
WARNING: moving release [ artifactory ] from [[ 5.9.1 ]] to [[ test1 ]] might not correctly connect to existing volumes. Check https://github.com/Praqma/helmsman/blob/master/docs/how_to/move_charts_across_namespaces.md for details if this release uses PV and PVC. -- priority: -2
2018/08/23 14:26:05 INFO: completed successfully!
```

I can see that the app is running:
```bash
helm ls --tiller-namespace=test1 --output yaml
Next: ""
Releases:
- AppVersion: 5.9.1
  Chart: artifactory-7.0.6
  Name: artifactory
  Namespace: test1
  Revision: 1
  Status: DEPLOYED
  Updated: Thu Aug 23 13:58:23 2018
```

And if I run `helmsman -f myfile.yaml --apply` the app is reinstalled.

So Helmsman is trying to move the release from namespace `[[ 5.9.1 ]]` to `[[ test1 ]]`, there is no namespace called `5.9.1` it is actually the `AppVersion: 5.9.1` from the Helm chart.
The initial release is already running properly on namespace `test1`.

Maybe I have something misconfigured on my desired state file?

### PR DESCRIPTION
**Pull request by luisdavim**
This fixes #61 by changing the `helm_helpers` to use the `json` output from helm instead of relying on the table output, this should also make `helmsman` more resilient to `helm`'s out put changes.

### CODE REVIEW

**Comment by epierotto** [comment]
I've tested this PR and solves #61 
```bash
./helmsman -f ~/sandbox/helmsman/myfile.yaml
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_|version: v1.4.0-rc-1535361673
A Helm-Charts-as-Code tool.


2018/08/27 10:24:55 INFO: Parsed YAML [[ /Users/epierotto/sandbox/helmsman/myfile.yaml ]] successfully and found [ 1 ] apps.
2018/08/27 10:24:55 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ logging ].
2018/08/27 10:24:55 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ monitoring ].
2018/08/27 10:24:55 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ production ].
2018/08/27 10:24:55 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ test1 ].
2018/08/27 10:24:56 WARN: I could not create namespace [logging ]. It already exists. I am skipping this.
2018/08/27 10:24:56 WARN: I could not create namespace [monitoring ]. It already exists. I am skipping this.
2018/08/27 10:24:57 WARN: I could not create namespace [production ]. It already exists. I am skipping this.
2018/08/27 10:24:57 WARN: I could not create namespace [test1 ]. It already exists. I am skipping this.
2018/08/27 10:24:57 INFO: deploying Tiller in namespace [ kube-system ].
2018/08/27 10:24:58 INFO: deploying Tiller in namespace [ test1 ].
2018/08/27 10:25:08 INFO: checking what I need to do for your charts ...
2018/08/27 10:25:08 INFO: mapping the current helm state ...
2018/08/27 10:25:14 INFO: checking if any Helmsman managed releases are no longer tracked by your desired state ...
2018/08/27 10:25:14 INFO: no untracked releases found.
2018/08/27 10:25:14 INFO: sorting the commands in the plan based on priorities (order flags) ...
----------------------
2018/08/27 10:25:14 INFO: Plan generated at: Mon Aug 27 2018 09:25:08
DECISION: release [ artifactory ] is desired to be enabled and is currently enabled.I will upgrade it in case you changed your values.yaml! -- priority: -2
2018/08/27 10:25:14 INFO: completed successfully!
```

```bash
helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
```

**Comment by luisdavim** [comment]
@sami-alajrami could you look into merging this? Thanks

**Comment by sami-alajrami** [comment]
thanks @luisdavim and apologies for the delay.. lgtm

**Comment by sami-alajrami** [comment]
as this breaks backwards compatibility with helm versions below v2.10.0-rc.1 (which don't have json output) , I am adding a check for the version to allow json to be used on newer versions and process the string output (as before) for older versions.

**Comment by luisdavim** [comment]
Do we really need to support older versions?

**Pull request merged**
