### PR TITLE
replace deprecated helm-secrets repo

### PR DESCRIPTION
**Pull request by antoinedeschenes**
Helm plugin is currently maintained here: https://github.com/jkroepke/helm-secrets

### CODE REVIEW

**Comment by antoinedeschenes** [comment]
The newer plugin versions work for us, but having someone else testing this could help

**Comment by luisdavim** [comment]
can you check why the tests are failing? I think you might have to also change the Circle CI config.

**Comment by antoinedeschenes** [comment]
Got it. Looks like sops was installed through the deprecated plugin previously. That was just removed in the latest version of v3.

**Comment by antoinedeschenes** [comment]
Should `sops` be installed with `make helmPlugins`?

**Comment by luisdavim** [comment]
> Should `sops` be installed with `make helmPlugins`?

Probably yes, either in `helmPlugins` or in `tools`...

**Pull request merged**
