### PR TITLE
Limit bash usage

### PR DESCRIPTION
**Pull request by kpucynski**
Lower amount of wrapping - remove bash and call commands directly.

### CODE REVIEW

**Comment by luisdavim** [comment]
this is already covered in https://github.com/Praqma/helmsman/pull/287 if we don't get an update from the author soon we can merge this instead.

**Comment by luisdavim** [comment]
oh, he did update his PR...

**Comment by kpucynski** [comment]
heh, I didn't saw this PR :D
I'll check.

**Comment by kpucynski** [comment]
haha we did basically the same :D
lucky guy was faster ;)
closing.

**Pull request closed without merging**
