### PR TITLE
Adds the ability to specify multiple dsf files with repeated -f argum…

### PR DESCRIPTION
**Pull request by norwoodj**
…ents #62

### CODE REVIEW

**Comment by luisdavim** [comment]
I think this will be very useful for our use cases.

**Comment by luisdavim** [comment]
@sami-alajrami could you look into merging this? Thanks

**Comment by norwoodj** [comment]
@sami-alajrami I've been using a custom built version with these changes for a week or so now with no difficulties. This feature is a must-have for us, can we get this merged soon?

**Comment by sami-alajrami** [comment]
thanks @norwoodj .. lgtm

**Pull request merged**
