### PR TITLE
adding flag to disable namespace creation

### PR DESCRIPTION
**Pull request by luisdavim**
trying to address #100

### CODE REVIEW

**Comment by sami-alajrami** [comment]
this could be addressed in a more comprehensive approach by trying to address #65 .. it might be better to prevent creating anything in the cluster (namespaces, Tiller deploys, service accounts  etc) if the `--apply` is not used. I haven't checked in detail yet what impacts this would have on generating a plan .. what do you think @luisdavim ?

**Comment by luisdavim** [comment]
makes sense, I'll look into that.

**Comment by luisdavim** [comment]
@sami-alajrami I didn't had much time to work on this before but I think that with the changes that I've pushed today, this should address both #65 and #100 . can you take a look and let me know what you think?

I've kept the `--no-ns` flag anyway because users like @bobhenkel might still need it.

**Comment by sami-alajrami** [comment]
thanks @luisdavim .. I will have a look today.

**Comment by sami-alajrami** [comment]
this looks good .. thanks again @luisdavim :)

**Pull request merged**
