### PR TITLE
Fix for helm charts without a latest version? 

### PR DESCRIPTION
**Pull request by ctr26**
https://github.com/Praqma/helmsman/issues/512

I've had a crack at fixing the bug I described here for the case where helm charts don't have a latest version.

### CODE REVIEW

**Comment by antoinedeschenes** [comment]
You should probably use the output from "getChartVersion" when calling "extractChartName", version can be a semver expression otherwise

**Comment by antoinedeschenes** [comment]
This also allows helmsman to work when a repository has a broken latest release

**Comment by mkubaczyk** [comment]
closing in favour of #532 :-)

**Comment by ctr26** [comment]
https://github.com/Praqma/helmsman/pull/532#issuecomment-723256091

This pull request may need reopening.

**Pull request closed without merging**
