### PR TITLE
adding helm diff to the decision maker

### PR DESCRIPTION
**Pull request by luisdavim**
Here's an example output:
```
$ helmsman -f helmsman-common.yaml -f dev/helmsman-dev.yaml
 _          _
| |        | |
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | |
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_|version: v1.5.0
A Helm-Charts-as-Code tool.


2018/09/09 13:31:16 INFO: Parsed YAML [[ helmsman-common.yaml ]] successfully and found [ 0 ] apps.
2018/09/09 13:31:16 INFO: Parsed YAML [[ dev/helmsman-dev.yaml ]] successfully and found [ 1 ] apps.
2018/09/09 13:31:16 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ kube-system ].
2018/09/09 13:31:16 INFO: namespace validation -- Tiller is desired to be deployed WITHOUT TLS in namespace [ dev ].
2018/09/09 13:31:19 WARN: I could not create namespace [dev ]. It already exists. I am skipping this.
2018/09/09 13:31:20 WARN: I could not create namespace [kube-system ]. It already exists. I am skipping this.
2018/09/09 13:31:20 INFO: deploying Tiller in namespace [ dev ].
2018/09/09 13:31:28 INFO: checking what I need to do for your charts ...
2018/09/09 13:31:28 INFO: mapping the current helm state ...
dev, artifactory-artifactory, Ingress (extensions) has been added:
-
+ # Source: artifactory/templates/ingress.yaml
+ apiVersion: extensions/v1beta1
+ kind: Ingress
+ metadata:
+   name: artifactory-artifactory
+   labels:
+     app: artifactory
+     chart: artifactory-7.0.6
+     release: artifactory
+     heritage: Tiller
+   annotations:
+ spec:
+   rules:
+     - host: artifactory.domain.example
+       http:
+         paths:
+           - path: /
+             backend:
+               serviceName: artifactory-artifactory
+               servicePort: 8081

2018/09/09 13:31:34 INFO: checking if any Helmsman managed releases are no longer tracked by your desired state ...
2018/09/09 13:31:35 INFO: no untracked releases found.
2018/09/09 13:31:35 INFO: sorting the commands in the plan based on priorities (order flags) ...
----------------------
2018/09/09 13:31:35 INFO: Plan generated at: Sun Sep  9 2018 12:31:28
DECISION: release [ artifactory ] is desired to be enabled and is currently enabled. I will upgrade it! -- priority: -2
2018/09/09 13:31:35 INFO: completed successfully!
```

### CODE REVIEW

**Comment by luisdavim** [comment]
Also fixes #72

**Comment by sami-alajrami** [comment]
@luisdavim based on this feature, the helmsman docker image need to include the diff plugin after this line
https://github.com/Praqma/helmsman/blob/998ef6f508cdd449dab51a493eb27d1bfcd55322/dockerfile/dockerfile#L38

**Comment by luisdavim** [comment]
right, sorry I forgot that. I'll add it in a second.

**Comment by sami-alajrami** [comment]
also in the test image https://github.com/Praqma/helmsman/blob/master/test_files/dockerfile :)

**Comment by luisdavim** [comment]
done.

**Comment by sami-alajrami** [comment]
helm diff does not seem to play nicely in containers (at least with circleci) because it creates files with UID/GID values that are higher than Docker and CircleCI can use. More details [here](https://circleci.com/gh/Praqma/helmsman/210) 
Trying to install it inside a running container in circleci also fails and shows the culprit files see [here](https://circleci.com/gh/Praqma/helmsman/218)
```
tar: diff/bin/diff: Cannot change ownership to uid 533217279, gid 2071383985: Invalid argument
tar: diff: Cannot change ownership to uid 533217279, gid 2071383985: Invalid argument
tar: Exiting with failure status due to previous errors
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
Exited with code 1
```

**Comment by luisdavim** [comment]
That is strange. It must be something on this script https://github.com/databus23/helm-diff/blob/master/install-binary.sh I'll take a better look once I'm on a computer.

**Comment by luisdavim** [comment]
I think the problem is that those commands are being executed as `root` and by default `tar` tries to preserve the ownership of the files in the archive if it's being executed by root,  I think that our options are, either open a PR on the `helm-diff` install script to add the `--no-same-owner` flag to the command extracting the archive, or we install the plugin using our own script instead of `helm plugin install` or we change the user in the docker files by using `USER`. I think that the last option is the best one.

**Comment by luisdavim** [comment]
#76 should fix this.

**Pull request merged**
