### PR TITLE
Update circleci to build/push to artifactory instead of upstream repo

### PR DESCRIPTION
**Pull request by bbetter173**

### CODE REVIEW

**Comment by mkubaczyk** [comment]
is it unintentional?

**Comment by luisdavim** [comment]
@bbetter173 this seems odd, can you explain the goal here?

**Comment by luisdavim** [comment]
I've closed the PR please open an issue to discuss what you're aiming to address.

**Comment by SwitchTV-BenBettridge** [comment]
Sorry guys, I've done this a handful of times in the last 24 hours while hacking some stuff together to test internally.

+1 to GitHub allowing forks to be disassociated with their upstream repositories.

**Pull request closed without merging**
