### PR TITLE
Add appsTemplates omitempty YAML key to allow YAML anchors in state file

### PR DESCRIPTION
**Pull request by mkubaczyk**
The feature request #300 with ignored keys in YAML state file, where such keys can be used as YAML anchors to follow DRY rule is really valuable, so I thought of the simplest way to do this. Hence the PR I created with the least change I could do to achieve that.

### CODE REVIEW

**Comment by mkjmdski** [comment]
thanks!

**Comment by mkubaczyk** [comment]
@sami-alajrami @luisdavim how you guys find it?

**Comment by luisdavim** [comment]
have you tested it? as long as this doesn't break the `toml` DSF I'm fine with it.

**Comment by mkubaczyk** [comment]
@luisdavim yes, it's working fine with yamls while at the same time not impacting tomls at all. Should I merge then?

**Pull request merged**
